### ISSUE TITLE
TWR activation of flight plans do not show up as activated on APP end

### ISSUE THREAD

**Issue by zkaviator** [vatSys/new-zealand-dataset#70]
When a flight plan gets activated by a TWR controller, it does not register as activated on the APP / ENR controller end when the TWR controller is using a ACU or ENR profile. On the TWR side, the next controller's field is blank while the APP controller does not see the individual flight plan as activated.

![Screenshot_1](https://user-images.githubusercontent.com/76762885/105674414-5a2d3f00-5f4c-11eb-8d65-f003969a29b2.png)

**Comment by sawbe** [comment]
DefaultJurisdiction.xml is not setup correctly. 
AssignSector Order="AA" <— AA is not a defined sector

**Comment by zkaviator** [comment]
> DefaultJurisdiction.xml is not setup correctly.
> AssignSector Order="AA" <— AA is not a defined sector

Will work on it in my fork and conduct a pull request onto this repo. Thanks

**Comment by zkaviator** [comment]
NOTE: Not a vatSys issue, now a issue with our dataset
